set_auto_on_off_enable:
  fields:
    config_entry:
      required: true
      selector:
        config_entry:
          integration: lamarzocco
    day_of_week:
      example: mon
      selector:
        select:
          options:
            - mon
            - tue
            - wed
            - thu
            - fri
            - sat
            - sun
    enable:
      example: "on"
      selector:
        select:
          options:
            - "on"
            - "off"

set_auto_on_off_times:
  fields:
    config_entry:
      required: true
      selector:
        config_entry:
          integration: lamarzocco
    day_of_week:
      example: mon
      selector:
        select:
          options:
            - mon
            - tue
            - wed
            - thu
            - fri
            - sat
            - sun
    hour_on:
      example: 6
      selector:
        number:
          min: 0
          max: 23
          step: 1
          mode: slider
    minute_on:
      example: 6
      selector:
        number:
          min: 0
          max: 59
          step: 1
          mode: slider
    hour_off:
      example: 5
      selector:
        number:
          min: 0
          max: 23
          step: 1
          mode: slider
    minute_off:
      example: 10
      selector:
        number:
          min: 0
          max: 59
          step: 1
          mode: slider

set_dose:
  fields:
    config_entry:
      required: true
      selector:
        config_entry:
          integration: lamarzocco
    key:
      example: 1
      selector:
        number:
          min: 1
          max: 4
          step: 1
          mode: slider
    pulses:
      example: 122
      selector:
        number:
          min: 0
          max: 999
          step: 1
          mode: slider

set_dose_hot_water:
  fields:
    config_entry:
      required: true
      selector:
        config_entry:
          integration: lamarzocco
    seconds:
      example: 8
      selector:
        number:
          min: 0
          max: 30
          step: 1
          mode: slider

set_prebrew_times:
  fields:
    config_entry:
      required: true
      selector:
        config_entry:
          integration: lamarzocco
    key:
      example: 1
      selector:
        number:
          min: 1
          max: 4
          step: 1
          mode: slider
    seconds_on:
      example: 1.1
      selector:
        number:
          min: 0
          max: 5.9
          step: 0.1
          mode: slider
    seconds_off:
      example: 1.1
      selector:
        number:
          min: 0
          max: 5.9
          step: 0.1
          mode: slider

set_preinfusion_time:
  fields:
    config_entry:
      required: true
      selector:
        config_entry:
          integration: lamarzocco
    key:
      example: 1
      selector:
        number:
          min: 1
          max: 4
          step: 1
          mode: slider
    seconds:
      example: 1.1
      selector:
        number:
          min: 0
          max: 24.9
          step: 0.1
          mode: slider
